stages:
  - test
  - deploy

test:
  image: ${CI_REGISTRY}/traque/ont-docker-base/ont-base-python:3.10
  stage: test
  before_script:
    - pip install .
  script:
    - pygmentize -L lexers
    - pygmentize -L lexers | grep "dorado"
    - mkdocs build --strict --verbose --site-dir test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  image: ${CI_REGISTRY}/traque/ont-docker-base/ont-base-python:3.10
  stage: deploy
  before_script:
    - pip install .
  script:
    - pygmentize -L lexers
    - pygmentize -L lexers | grep "dorado"
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
  variables:
    PAGES_PREFIX: ""
  pages:
    path_prefix: "$PAGES_PREFIX"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on default branch (with default PAGES_PREFIX)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Conditionally change the prefix for Merge Requests
      variables:
        PAGES_PREFIX: "mr-$CI_MERGE_REQUEST_IID" # Prefix with the mr-<iid>, like `mr-123`
